### ISSUE TITLE
Publish the v.0.3.0

### ISSUE THREAD

**Issue by apomalyn** [unitedideasco/system_windows#1]
Hi! 👋 

First, thank you a lot for this plugin! It's simple but saved me so much trouble, so once again: thank you 🙏 

Could you please publish the v0.3.0 on pub.dev, please? We are still in the 0.2.1 with the 'print' of all the active windows 😅 

Thank you again!

**Comment by jakub-stefaniak** [comment]
Hi! Thank you for using system_windows plugin. I will release new version in the nearest future with major improvements.

**Comment by jakub-stefaniak** [comment]
v0.3.0 is out. Closing this issue for now. If there are any new thoughts feel free to open new issue.
